name: test-and-build
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.1'
      - name: Run Unit Tests
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup golang
        uses: actions/setup-go@v2
      - name: Build
        run: make build

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out if Docker image builds
        uses: docker/build-push-action@v2
        with:
          context: .
          # The version increase step can only take place if this step has run through successfully.
          # One way to deal with this could be to push under the current commit-hash and re-tag it in a later step.
          # Currently the build step takes place twice which is a waste of resources.
          tags: |
            awamob/hello-go:deleteme
          # build on feature branches, push only on main branch
          push: false

      - name: Automated Version Bump
        id: version-bump
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DRY_RUN: ${{ github.ref != 'refs/heads/main' }}
      - run: echo "Version tag generated for this build is ${{ steps.version-bump.outputs.new_tag }}, but only applied if on main branch."

      - name: Build image and push to Docker Hub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          # Note: tags has to be all lower-case
          tags: |
            awamob/hello-go:${{ steps.version-bump.outputs.new_tag }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Inform infrastructure repository of a new release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: borismw/hello-infra
          event-type: update-version
          client-payload: '{ "k8s_namespace": "hello", "k8s_project": "hello-go", "env": "production", "docker_repo": "awamob/hello-go", "new_version": "${{ steps.version-bump.outputs.new_tag }}" }'